In [ ]:
#NumPy practice 

In [5]:
import numpy as np

In [2]:
lst = [[1,2,3],[4,5,6]]

In [3]:
ary1d = np.array(lst)
lst

[[1, 2, 3], [4, 5, 6]]

In [4]:
ary1d.dtype

dtype('int32')

In [5]:
float32_ary = ary1d.astype(np.float32)
float32_ary

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [7]:
ary2d = np.array(lst, dtype='int64')
ary2d.itemsize #size of single array element in bytes

8

In [8]:
ary2d.size #number of element in an array

6

In [9]:
ary2d.ndim

2

In [10]:
ary2d.shape

(2, 3)

In [11]:
np.array([1,2,3]).shape #always a tuple

(3,)

In [13]:
#Instead of passing lists or tuples to the array function, we can also
#provide a single float or integer, which will construct a zero-dimensional
#array (for instance, a representation of a scalar)

scalar = np.array(5)

In [14]:
scalar

array(5)

In [15]:
np.ones((3,3)) #all 1s

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros((3,3)) #all 0s

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.diag((3,3,3)) #diagonal matrix

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [19]:
np.arange(4.,10.)

array([4., 5., 6., 7., 8., 9.])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(1.,11., 2)

array([1., 3., 5., 7., 9.])

In [22]:
#The linspace function is especially useful if we want to create a particular number of evenly spaced values in a specified half-open interval:
np.linspace(0., 1., num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
ary = np.array([1,2,3])
ary[0]

1

In [24]:
ary[:2] #equal to ary[0:2]

array([1, 2])

In [27]:
ary = np.array([[1,2,3],[4,5,6]])
ary[0, 0] #upper left

1

In [28]:
ary[-1, -1] #lower right

6

In [29]:
ary[0, 1] # first row, second column

2

In [31]:
ary[0] # entire first row

array([1, 2, 3])

In [32]:
ary[:, 0] #entire first column

array([1, 4])

In [34]:
ary[:, :2] #first two columns

array([[1, 2],
       [4, 5]])

In [35]:
ary[0, 0]

1

In [2]:
lst = [[1, 2, 3], [4, 5, 6]]
for row_idx, row_val in enumerate(lst):
    for col_idx, col_val in enumerate(row_val):
        lst[row_idx][col_idx] += 1
lst        

[[2, 3, 4], [5, 6, 7]]

In [3]:
lst = [[1, 2, 3], [4, 5, 6]]
[[cell + 1 for cell in row] for row in lst]
lst

[[1, 2, 3], [4, 5, 6]]

In [6]:
ary = np.array([[1, 2, 3], [4, 5, 6]])
ary = np.add(ary, 1)
ary

array([[2, 3, 4],
       [5, 6, 7]])

In [7]:
ary + 1

array([[3, 4, 5],
       [6, 7, 8]])

In [8]:
ary**2

array([[ 4,  9, 16],
       [25, 36, 49]], dtype=int32)

In [11]:
ary = np.array([[1, 2, 3],[4, 5, 6]])
np.add.reduce(ary) # column sums

array([5, 7, 9])

In [12]:
np.add.reduce(ary, axis=1) # row sums

array([ 6, 15])

In [13]:
ary.sum(axis=0) # column sums

array([5, 7, 9])

In [14]:
ary.sum()

21

In [15]:
ary1 = np.array([1, 2, 3])
ary2 = np.array([4, 5, 6])
ary1 + ary2

array([5, 7, 9])

In [16]:
ary3 = np.array([[4, 5, 6],[7, 8, 9]])
ary3 + ary1 # similarly, ary1 + ary3

array([[ 5,  7,  9],
       [ 8, 10, 12]])